// ignore_for_file: type=lint, unused_element, unused_field, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Bindings for timezone native library
class TimezoneBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TimezoneBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TimezoneBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Char> get_local_timezone() {
    return _get_local_timezone();
  }

  late final _get_local_timezonePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'get_local_timezone',
      );
  late final _get_local_timezone = _get_local_timezonePtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> get_timezone_abbreviation() {
    return _get_timezone_abbreviation();
  }

  late final _get_timezone_abbreviationPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'get_timezone_abbreviation',
      );
  late final _get_timezone_abbreviation = _get_timezone_abbreviationPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  int get_utc_offset_seconds() {
    return _get_utc_offset_seconds();
  }

  late final _get_utc_offset_secondsPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'get_utc_offset_seconds',
      );
  late final _get_utc_offset_seconds = _get_utc_offset_secondsPtr
      .asFunction<int Function()>();

  void free_timezone_string(ffi.Pointer<ffi.Char> str) {
    return _free_timezone_string(str);
  }

  late final _free_timezone_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'free_timezone_string',
      );
  late final _free_timezone_string = _free_timezone_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}
